//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllocationsCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveTradeSummary
    {
        public int trade_id { get; set; }
        public string trade_uri { get; set; }
        public string service_code { get; set; }
        public string length_type_label { get; set; }
        public string trade_editorial_label { get; set; }
        public string structure_type_label { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
        public Nullable<System.DateTime> published_on { get; set; }
        public Nullable<decimal> instruction_entry { get; set; }
        public Nullable<System.DateTime> instruction_entry_date { get; set; }
        public Nullable<decimal> instruction_exit { get; set; }
        public Nullable<System.DateTime> instruction_exit_date { get; set; }
        public string instruction_label { get; set; }
        public string hedge_label { get; set; }
        public string instruction_type_label { get; set; }
        public string absolute_performance { get; set; }
        public string absolute_performance_ytd { get; set; }
        public string absolute_measure_type { get; set; }
        public string absolute_currency_code { get; set; }
        public string relative_performance { get; set; }
        public string relative_performance_ytd { get; set; }
        public string relative_measure_type { get; set; }
        public string benchmark_label { get; set; }
        public string relative_currency_code { get; set; }
        public string comment_label { get; set; }
        public Nullable<decimal> mark_to_market_rate { get; set; }
        public Nullable<decimal> interest_rate { get; set; }
        public Nullable<bool> isOpen { get; set; }
        public Nullable<bool> isClosedFor7DaysOrMore { get; set; }
        public string parent_trade_editorial_label { get; set; }
    }
}
