//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllocationsCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allocation
    {
        public Allocation()
        {
            this.Allocation1 = new HashSet<Allocation>();
            this.AllocationValues = new HashSet<AllocationValue>();
            this.Comments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Instrument_tradable_thing_id { get; set; }
        public Nullable<int> ParentAllocation_Id { get; set; }
        public Nullable<int> Portfolio_Id { get; set; }
        public string Uri { get; set; }
        public Nullable<System.DateTime> FirstPublishedDate { get; set; }
        public Nullable<int> Status_status_id { get; set; }
    
        public virtual ICollection<Allocation> Allocation1 { get; set; }
        public virtual Allocation Allocation2 { get; set; }
        public virtual Portfolio Portfolio { get; set; }
        public virtual Status Status { get; set; }
        public virtual Tradable_Thing Tradable_Thing { get; set; }
        public virtual ICollection<AllocationValue> AllocationValues { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
