//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllocationsCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllocationHistorySummary
    {
        public long Id { get; set; }
        public Nullable<int> AllocationId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<float> CurrentAllocation { get; set; }
        public string CurrentAllocationWeighting { get; set; }
        public string CurrentBenchmarkWeighting { get; set; }
        public Nullable<float> CurrentBenchmarkMin { get; set; }
        public Nullable<float> CurrentBenchmarkMax { get; set; }
        public Nullable<float> PreviousAllocation { get; set; }
        public string PreviousAllocationWeighting { get; set; }
        public string PreviousBenchmarkWeighting { get; set; }
        public Nullable<float> PreviousBenchmarkMin { get; set; }
        public Nullable<float> PreviousBenchmarkMax { get; set; }
        public Nullable<float> CurrentBenchmark { get; set; }
        public Nullable<float> PreviousBenchmark { get; set; }
        public string AbsolutePerformance { get; set; }
        public string RelativePerformance { get; set; }
        public string Benchmark { get; set; }
        public string Comment { get; set; }
    }
}
