//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllocationsCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllocationSummary
    {
        public int Id { get; set; }
        public string Uri { get; set; }
        public Nullable<float> CurrentAllocation { get; set; }
        public string CurrentAllocationWeighting { get; set; }
        public Nullable<float> PreviousAllocation { get; set; }
        public string PreviousAllocationWeighting { get; set; }
        public Nullable<float> CurrentBenchmark { get; set; }
        public Nullable<float> CurrentBenchmarkMin { get; set; }
        public Nullable<float> CurrentBenchmarkMax { get; set; }
        public string CurrentBenchmarkWeighting { get; set; }
        public Nullable<float> PreviousBenchmark { get; set; }
        public Nullable<float> PreviousBenchmarkMin { get; set; }
        public Nullable<float> PreviousBenchmarkMax { get; set; }
        public string PreviousBenchmarkWeighting { get; set; }
        public string AbsolutePerformance { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<System.DateTime> FirstPublishedDate { get; set; }
        public Nullable<int> ParentAllocation_Id { get; set; }
        public Nullable<int> Portfolio_Id { get; set; }
        public string AbsolutePerformanceMeasure { get; set; }
        public string Currency { get; set; }
        public string Instrument { get; set; }
        public string InstrumentUri { get; set; }
        public string Status { get; set; }
        public Nullable<int> StatusId { get; set; }
    }
}
