//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllocationsCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllocationValue
    {
        public int Id { get; set; }
        public Nullable<float> Allocation { get; set; }
        public Nullable<float> BenchmarkValue { get; set; }
        public Nullable<float> BenchmarkMinValue { get; set; }
        public Nullable<float> BenchmarkMaxValue { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> AllocationWeighting_Id { get; set; }
        public Nullable<int> BenchmarkWeighting_Id { get; set; }
        public Nullable<int> Allocation_Id { get; set; }
    
        public virtual Allocation Allocation1 { get; set; }
        public virtual WeightingDescription WeightingDescription { get; set; }
        public virtual WeightingDescription WeightingDescription1 { get; set; }
    }
}
