//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllocationsCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> Allocation_Id { get; set; }
        public Nullable<int> Portfolio_Id { get; set; }
    
        public virtual Allocation Allocation { get; set; }
        public virtual Portfolio Portfolio { get; set; }
    }
}
