//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllocationsCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instruction_Type
    {
        public Instruction_Type()
        {
            this.Trade_Instruction = new HashSet<Trade_Instruction>();
        }
    
        public int instruction_type_id { get; set; }
        public string instruction_type_label { get; set; }
    
        public virtual ICollection<Trade_Instruction> Trade_Instruction { get; set; }
    }
}
