//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllocationsCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkedTrade
    {
        public int trade_id { get; set; }
        public int related_trade_id { get; set; }
        public string trade_editorial_label { get; set; }
        public Nullable<int> linked_trade_count { get; set; }
    }
}
