//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllocationsCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measure_Type
    {
        public Measure_Type()
        {
            this.Performances = new HashSet<Performance>();
        }
    
        public int measure_type_id { get; set; }
        public string measure_type_label { get; set; }
    
        public virtual ICollection<Performance> Performances { get; set; }
    }
}
