//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllocationsCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portfolio
    {
        public Portfolio()
        {
            this.Allocations = new HashSet<Allocation>();
            this.Comments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string PerformanceModel { get; set; }
        public Nullable<int> Benchmark_benchmark_id { get; set; }
        public Nullable<int> Duration_Id { get; set; }
        public Nullable<int> Service_service_id { get; set; }
        public Nullable<int> Status_status_id { get; set; }
        public Nullable<int> Type_Id { get; set; }
        public string Uri { get; set; }
        public Nullable<System.DateTime> FirstPublishedDate { get; set; }
    
        public virtual ICollection<Allocation> Allocations { get; set; }
        public virtual Benchmark Benchmark { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual DurationType DurationType { get; set; }
        public virtual PortfolioType PortfolioType { get; set; }
        public virtual Service Service { get; set; }
        public virtual Status Status { get; set; }
    }
}
