//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllocationsCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relativity
    {
        public Relativity()
        {
            this.Positions = new HashSet<Position>();
            this.Trade_Instruction = new HashSet<Trade_Instruction>();
            this.Trades = new HashSet<Trade>();
        }
    
        public int relativity_id { get; set; }
        public string relativity_label { get; set; }
    
        public virtual ICollection<Position> Positions { get; set; }
        public virtual ICollection<Trade_Instruction> Trade_Instruction { get; set; }
        public virtual ICollection<Trade> Trades { get; set; }
    }
}
