//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllocationsCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Allocations = new HashSet<Allocation>();
            this.Portfolios = new HashSet<Portfolio>();
            this.Trades = new HashSet<Trade>();
        }
    
        public int status_id { get; set; }
        public string status_label { get; set; }
    
        public virtual ICollection<Allocation> Allocations { get; set; }
        public virtual ICollection<Portfolio> Portfolios { get; set; }
        public virtual ICollection<Trade> Trades { get; set; }
    }
}
