//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllocationsCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track_Record_Type
    {
        public Track_Record_Type()
        {
            this.Track_Record = new HashSet<Track_Record>();
        }
    
        public int track_record_type_id { get; set; }
        public string track_record_type_label { get; set; }
    
        public virtual ICollection<Track_Record> Track_Record { get; set; }
    }
}
