//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllocationsCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trade
    {
        public Trade()
        {
            this.Related_Trade = new HashSet<Related_Trade>();
            this.Related_Trade1 = new HashSet<Related_Trade>();
            this.Track_Record = new HashSet<Track_Record>();
            this.Trade_Comment = new HashSet<Trade_Comment>();
            this.Trade_Instruction = new HashSet<Trade_Instruction>();
            this.Trade_Line = new HashSet<Trade_Line>();
        }
    
        public int trade_id { get; set; }
        public string trade_uri { get; set; }
        public Nullable<int> relativity_id { get; set; }
        public Nullable<int> length_type_id { get; set; }
        public Nullable<int> structure_type_id { get; set; }
        public Nullable<int> service_id { get; set; }
        public Nullable<int> currency_id { get; set; }
        public Nullable<int> benchmark_id { get; set; }
        public string trade_label { get; set; }
        public string trade_editorial_label { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> published_on { get; set; }
    
        public virtual Benchmark Benchmark { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Length_Type Length_Type { get; set; }
        public virtual ICollection<Related_Trade> Related_Trade { get; set; }
        public virtual ICollection<Related_Trade> Related_Trade1 { get; set; }
        public virtual Relativity Relativity { get; set; }
        public virtual Service Service { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual Structure_Type Structure_Type { get; set; }
        public virtual ICollection<Track_Record> Track_Record { get; set; }
        public virtual ICollection<Trade_Comment> Trade_Comment { get; set; }
        public virtual ICollection<Trade_Instruction> Trade_Instruction { get; set; }
        public virtual ICollection<Trade_Line> Trade_Line { get; set; }
    }
}
