//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllocationsCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeLineSummary
    {
        public Nullable<int> trade_id { get; set; }
        public int trade_line_id { get; set; }
        public string trade_line_label { get; set; }
        public string trade_line_editorial_label { get; set; }
        public string trade_line_group_label { get; set; }
        public int trade_line_group_id { get; set; }
        public string trade_line_group_editorial_label { get; set; }
        public int trade_line_group_type_id { get; set; }
        public string trade_line_group_type_label { get; set; }
        public int tradable_thing_id { get; set; }
        public string tradable_thing_uri { get; set; }
        public string tradable_thing_code { get; set; }
        public string tradable_thing_label { get; set; }
        public int tradable_thing_class_id { get; set; }
        public string tradable_thing_class_uri { get; set; }
        public string tradable_thing_class_label { get; set; }
        public string tradable_thing_class_editorial_label { get; set; }
        public int position_id { get; set; }
        public string position_uri { get; set; }
        public string position_label { get; set; }
        public int location_id { get; set; }
        public string location_label { get; set; }
    }
}
