//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllocationsCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeHistory
    {
        public long id { get; set; }
        public Nullable<int> trade_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string status { get; set; }
        public string instructions_type { get; set; }
        public string instructions_comments { get; set; }
        public string mark_to_market_rate { get; set; }
        public string interest_rate { get; set; }
        public string spot { get; set; }
        public string carry { get; set; }
        public string absolute_performance { get; set; }
        public string relative_performance { get; set; }
        public string return_performance_benchmark { get; set; }
    }
}
