//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllocationsCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trade_Line_Group_Type
    {
        public Trade_Line_Group_Type()
        {
            this.Trade_Line_Group = new HashSet<Trade_Line_Group>();
        }
    
        public int trade_line_group_type_id { get; set; }
        public string trade_line_group_type_uri { get; set; }
        public string trade_line_group_type_label { get; set; }
    
        public virtual ICollection<Trade_Line_Group> Trade_Line_Group { get; set; }
    }
}
