//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllocationsCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tradable_Thing_Class
    {
        public Tradable_Thing_Class()
        {
            this.Tradable_Thing = new HashSet<Tradable_Thing>();
        }
    
        public int tradable_thing_class_id { get; set; }
        public string tradable_thing_class_uri { get; set; }
        public string tradable_thing_class_label { get; set; }
        public string tradable_thing_class_editorial_label { get; set; }
    
        public virtual ICollection<Tradable_Thing> Tradable_Thing { get; set; }
    }
}
