//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllocationsCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trade_Instruction
    {
        public int trade_instruction_id { get; set; }
        public Nullable<int> trade_id { get; set; }
        public Nullable<int> relativity_id { get; set; }
        public Nullable<int> instruction_type_id { get; set; }
        public Nullable<int> hedge_id { get; set; }
        public Nullable<decimal> instruction_entry { get; set; }
        public Nullable<System.DateTime> instruction_entry_date { get; set; }
        public Nullable<decimal> instruction_exit { get; set; }
        public Nullable<System.DateTime> instruction_exit_date { get; set; }
        public string instruction_label { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
    
        public virtual Hedge_Type Hedge_Type { get; set; }
        public virtual Instruction_Type Instruction_Type { get; set; }
        public virtual Relativity Relativity { get; set; }
        public virtual Trade Trade { get; set; }
    }
}
