//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllocationsCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeightingDescription
    {
        public WeightingDescription()
        {
            this.AllocationValues = new HashSet<AllocationValue>();
            this.AllocationValues1 = new HashSet<AllocationValue>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<AllocationValue> AllocationValues { get; set; }
        public virtual ICollection<AllocationValue> AllocationValues1 { get; set; }
    }
}
